"""
Django settings for medisoft project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^x+bwnq6y7h5tb40ln%8b_s%xud&m@(%#9c#tsz&(mp7k9seu^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',
]

AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.SessionFixMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medisoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medisoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'medisoft.backends.mysql',
        'NAME': 'medisoft',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login URL for @login_required decorator
LOGIN_URL = '/api/auth/login/'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Session settings – ensure cookies work through Vite proxy in development
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 weeks (default)

# bKash Payment Gateway Configuration (Tokenized Checkout)
# Use sandbox for development, switch to production for live payments
BKASH = {
    'app_key': '',
    'app_secret': '',
    'username': 'sandbox',
    'password': 'sandbox',
    'sandbox': True,
    'success_url': 'http://localhost:5173/payments/success',
    'fail_url': 'http://localhost:5173/payments/fail',
    'cancel_url': 'http://localhost:5173/payments/cancel',
    'ipn_url': 'http://127.0.0.1:8000/api/payments/bkash/ipn/',
}

# bKash API URLs
BKASH_API = {
    'sandbox': {
        'base': 'https://sandbox.pay.bkauniv.com/merchantained/v1.2.0-beta',
        'grant_token': '/tokenized/checkout/grant/token',
        'create_payment': '/tokenized/checkout/create',
        'query_payment': '/tokenized/checkout/payment/status',
        'refund': '/tokenized/checkout/payment/refund',
    },
    'production': {
        'base': 'https://tokenized.pay.bkauniv.com/merchantained/v1.2.0-beta',
        'grant_token': '/tokenized/checkout/grant/token',
        'create_payment': '/tokenized/checkout/create',
        'query_payment': '/tokenized/checkout/payment/status',
        'refund': '/tokenized/checkout/payment/refund',
    },
}

# Default service prices (BDT) for auto-population when selecting category
SERVICE_DEFAULT_PRICES = {
    'Appointment': 500.00,
    'SeatBooking': 1500.00,
    'MedicineOrder': 0.00,
    'LabBooking': 800.00,
    'Ambulance': 1200.00,
}
