# Generated by Django 6.0.6 on 2026-06-13 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulance_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('ambulance_type', models.CharField(choices=[('Basic', 'Basic'), ('ALS', 'Advanced Life Support'), ('BLS', 'Basic Life Support'), ('ICU', 'ICU Ambulance')], default='Basic', max_length=20)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_phone', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=1)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On-Trip', 'On-Trip'), ('Maintenance', 'Maintenance'), ('Offline', 'Offline')], default='Available', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ambulances',
            },
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='booking_type',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Scheduled', 'Scheduled'), ('Transfer', 'Transfer')], default='Emergency', max_length=15),
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='ambulance',
            field=models.ForeignKey(blank=True, db_column='ambulance_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.ambulance'),
        ),
    ]
